// Mock data for UFC fights
export const mockFights = [
  {
    id: "fight1",
    fighterA: "Jon Jones",
    fighterB: "Ciryl Gane",
    date: "May 15, 2023",
    openingOdds: -150,
    currentOdds: -220,
  },
  {
    id: "fight2",
    fighterA: "Israel Adesanya",
    fighterB: "Alex Pereira",
    date: "May 22, 2023",
    openingOdds: 120,
    currentOdds: -110,
  },
  {
    id: "fight3",
    fighterA: "Amanda Nunes",
    fighterB: "Julianna Peña",
    date: "June 5, 2023",
    openingOdds: -200,
    currentOdds: -180,
  },
  {
    id: "fight4",
    fighterA: "Dustin Poirier",
    fighterB: "Charles Oliveira",
    date: "June 12, 2023",
    openingOdds: 150,
    currentOdds: 180,
  },
  {
    id: "fight5",
    fighterA: "Kamaru Usman",
    fighterB: "Leon Edwards",
    date: "June 19, 2023",
    openingOdds: -170,
    currentOdds: -120,
  },
  {
    id: "fight6",
    fighterA: "Francis Ngannou",
    fighterB: "Stipe Miocic",
    date: "July 8, 2023",
    openingOdds: -130,
    currentOdds: -250,
  },
]

// Mock data for sentiment vs odds
export const mockSentimentData: Record<string, any[]> = {
  fight1: [
    { date: "2023-04-15", sentiment: 65, odds: -150, keyTweet: "Jones looks in the best shape of his career!" },
    { date: "2023-04-22", sentiment: 68, odds: -160 },
    { date: "2023-04-29", sentiment: 72, odds: -180, keyTweet: "Jones' wrestling will be too much for Gane." },
    { date: "2023-05-06", sentiment: 75, odds: -200 },
    {
      date: "2023-05-13",
      sentiment: 78,
      odds: -220,
      keyTweet: "After watching Jones' training videos, I can't see how Gane wins this.",
    },
  ],
  fight2: [
    { date: "2023-04-22", sentiment: 45, odds: 120, keyTweet: "Adesanya needs to be careful of Pereira's left hook." },
    { date: "2023-04-29", sentiment: 48, odds: 100 },
    { date: "2023-05-06", sentiment: 52, odds: 50, keyTweet: "Adesanya's improved takedown defense will be key." },
    { date: "2023-05-13", sentiment: 58, odds: 0 },
    { date: "2023-05-20", sentiment: 62, odds: -110, keyTweet: "Adesanya looks faster than ever in training camp!" },
  ],
  default: [
    { date: "2023-04-15", sentiment: 50, odds: -100 },
    { date: "2023-04-22", sentiment: 55, odds: -120 },
    { date: "2023-04-29", sentiment: 60, odds: -140 },
    { date: "2023-05-06", sentiment: 65, odds: -160 },
    { date: "2023-05-13", sentiment: 70, odds: -180 },
  ],
}

// Mock data for fight predictions
export const mockPredictions: Record<string, any> = {
  fight1: {
    predictedWinner: "fighterA",
    confidence: 78,
    fighterAProb: 78,
    fighterBProb: 22,
  },
  fight2: {
    predictedWinner: "fighterB",
    confidence: 65,
    fighterAProb: 35,
    fighterBProb: 65,
  },
  fight3: {
    predictedWinner: "fighterA",
    confidence: 82,
    fighterAProb: 82,
    fighterBProb: 18,
  },
  fight4: {
    predictedWinner: "fighterB",
    confidence: 58,
    fighterAProb: 42,
    fighterBProb: 58,
  },
  fight5: {
    predictedWinner: "fighterA",
    confidence: 68,
    fighterAProb: 68,
    fighterBProb: 32,
  },
  fight6: {
    predictedWinner: "fighterA",
    confidence: 75,
    fighterAProb: 75,
    fighterBProb: 25,
  },
}

// Mock data for social media posts
export const mockSocialPosts = [
  {
    id: "post1",
    fighterId: "A-fight1",
    username: "@ufcfan123",
    platform: "twitter",
    content: "Jon Jones is going to dominate Gane with his wrestling. No doubt about it!",
    timestamp: "2023-05-14T14:23:00",
    sentiment: "positive" as const,
  },
  {
    id: "post2",
    fighterId: "B-fight1",
    username: "MMAExpert",
    platform: "reddit",
    content: "Gane's striking is too technical. Jones hasn't faced anyone with this level of striking IQ.",
    timestamp: "2023-05-14T12:45:00",
    sentiment: "positive" as const,
  },
  {
    id: "post3",
    fighterId: "A-fight2",
    username: "@izzy_fan",
    platform: "twitter",
    content: "Adesanya learned from the last fight. He won't make the same mistakes again.",
    timestamp: "2023-05-14T10:12:00",
    sentiment: "positive" as const,
  },
  {
    id: "post4",
    fighterId: "B-fight2",
    username: "KnockoutKing",
    platform: "reddit",
    content: "Pereira's power is just too much. One left hook and it's over.",
    timestamp: "2023-05-14T09:30:00",
    sentiment: "positive" as const,
  },
  {
    id: "post5",
    fighterId: "A-fight3",
    username: "@nunes_goat",
    platform: "twitter",
    content: "Amanda looks unfocused in her recent interviews. I'm worried about her mindset.",
    timestamp: "2023-05-14T08:15:00",
    sentiment: "negative" as const,
  },
  {
    id: "post6",
    fighterId: "A-fight1",
    username: "JonesHater",
    platform: "reddit",
    content: "Jones is overrated. His last few performances have been mediocre at best.",
    timestamp: "2023-05-14T07:45:00",
    sentiment: "negative" as const,
  },
  {
    id: "post7",
    fighterId: "B-fight3",
    username: "@pena_believer",
    platform: "twitter",
    content: "Peña has the perfect style to beat Nunes. The first win wasn't a fluke.",
    timestamp: "2023-05-14T06:30:00",
    sentiment: "positive" as const,
  },
  {
    id: "post8",
    fighterId: "A-fight4",
    username: "@poirier_diamond",
    platform: "twitter",
    content: "Poirier's boxing is looking crisp in the training videos. His hands will be too fast for Oliveira.",
    timestamp: "2023-05-14T05:20:00",
    sentiment: "positive" as const,
  },
  {
    id: "post9",
    fighterId: "B-fight4",
    username: "OliveiraFan",
    platform: "reddit",
    content: "Charles' submission game is on another level. Poirier will be tapping out by round 2.",
    timestamp: "2023-05-14T04:15:00",
    sentiment: "positive" as const,
  },
  {
    id: "post10",
    fighterId: "A-fight5",
    username: "@usman_champ",
    platform: "twitter",
    content: "Usman seems distracted with all his media appearances. Not sure if he's focused on the fight.",
    timestamp: "2023-05-14T03:45:00",
    sentiment: "negative" as const,
  },
  {
    id: "post11",
    fighterId: "B-fight5",
    username: "EdwardsSupporter",
    platform: "reddit",
    content: "Edwards has improved so much. That head kick KO wasn't luck - it was skill and perfect timing.",
    timestamp: "2023-05-14T02:30:00",
    sentiment: "positive" as const,
  },
  {
    id: "post12",
    fighterId: "A-fight6",
    username: "@ngannou_power",
    platform: "twitter",
    content: "Ngannou's power is unmatched. No one can take those shots, not even Stipe.",
    timestamp: "2023-05-14T01:15:00",
    sentiment: "positive" as const,
  },
]

// Mock data for fighter profiles
export const mockFighterProfiles: Record<string, any> = {
  fighter1: {
    name: "Jon Jones",
    nickname: "Bones",
    age: 35,
    height: "6'4\" (193 cm)",
    weight: "248 lbs (112 kg)",
    reach: '84.5" (214 cm)',
    stance: "Orthodox",
    record: {
      total: 27,
      wins: 26,
      losses: 1,
      draws: 0,
      ko: 10,
    },
    stats: {
      strikingAccuracy: 58,
      strikesLandedPerMin: 4.3,
      strikesAbsorbedPerMin: 2.1,
      takedownAccuracy: 47,
      takedownDefense: 95,
      submissionAverage: 0.9,
    },
    recentFights: [
      {
        opponent: "Ciryl Gane",
        date: "March 4, 2023",
        result: "Win",
        method: "Submission (Guillotine Choke)",
      },
      {
        opponent: "Dominick Reyes",
        date: "February 8, 2020",
        result: "Win",
        method: "Decision (Unanimous)",
      },
      {
        opponent: "Thiago Santos",
        date: "July 6, 2019",
        result: "Win",
        method: "Decision (Split)",
      },
      {
        opponent: "Anthony Smith",
        date: "March 2, 2019",
        result: "Win",
        method: "Decision (Unanimous)",
      },
    ],
  },
  fighter2: {
    name: "Israel Adesanya",
    nickname: "The Last Stylebender",
    age: 33,
    height: "6'4\" (193 cm)",
    weight: "185 lbs (84 kg)",
    reach: '80" (203 cm)',
    stance: "Switch",
    record: {
      total: 24,
      wins: 21,
      losses: 3,
      draws: 0,
      ko: 15,
    },
    stats: {
      strikingAccuracy: 49,
      strikesLandedPerMin: 3.9,
      strikesAbsorbedPerMin: 2.7,
      takedownAccuracy: 28,
      takedownDefense: 77,
      submissionAverage: 0.1,
    },
    recentFights: [
      {
        opponent: "Alex Pereira",
        date: "April 8, 2023",
        result: "Win",
        method: "KO (Punch)",
      },
      {
        opponent: "Alex Pereira",
        date: "November 12, 2022",
        result: "Loss",
        method: "TKO (Punches)",
      },
      {
        opponent: "Jared Cannonier",
        date: "July 2, 2022",
        result: "Win",
        method: "Decision (Unanimous)",
      },
      {
        opponent: "Robert Whittaker",
        date: "February 12, 2022",
        result: "Win",
        method: "Decision (Unanimous)",
      },
    ],
  },
  fighter3: {
    name: "Amanda Nunes",
    nickname: "The Lioness",
    age: 34,
    height: "5'8\" (173 cm)",
    weight: "135 lbs (61 kg)",
    reach: '69" (175 cm)',
    stance: "Orthodox",
    record: {
      total: 23,
      wins: 21,
      losses: 2,
      draws: 0,
      ko: 13,
    },
    stats: {
      strikingAccuracy: 51,
      strikesLandedPerMin: 4.7,
      strikesAbsorbedPerMin: 2.8,
      takedownAccuracy: 54,
      takedownDefense: 82,
      submissionAverage: 0.7,
    },
    recentFights: [
      {
        opponent: "Julianna Peña",
        date: "July 30, 2022",
        result: "Win",
        method: "Decision (Unanimous)",
      },
      {
        opponent: "Julianna Peña",
        date: "December 11, 2021",
        result: "Loss",
        method: "Submission (Rear-Naked Choke)",
      },
      {
        opponent: "Megan Anderson",
        date: "March 6, 2021",
        result: "Win",
        method: "Submission (Reverse Triangle Armbar)",
      },
      {
        opponent: "Felicia Spencer",
        date: "June 6, 2020",
        result: "Win",
        method: "Decision (Unanimous)",
      },
    ],
  },
}
